name: Build & Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip extension
        run: |
          mkdir -p dist
          (cd src && zip -r ../dist/computed-css-inspector.zip .)
      - name: Upload artifact (builds on main)
        if: startsWith(github.ref, 'refs/heads/')
        uses: actions/upload-artifact@v4
        with:
          name: computed-css-inspector
          path: dist/computed-css-inspector.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip extension
        run: |
          mkdir -p dist
          (cd src && zip -r ../dist/computed-css-inspector.zip .)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/computed-css-inspector.zip
